component: scf
app: img-tf
name: img-tf
stage: dev

inputs:
  src:
    src: ./
    exclude:
      - .env
      - model
      - layer
      - node_modules/**
  region: ap-shanghai
  name: ${name}
  runtime: Nodejs12.16
  memorySize: 1024 # 内存大小，单位MB
  timeout: 60 # 超时时间，单位秒
  environment: #  环境变量
    variables: #  环境变量对象
      NODE_ENV: production
  handler: index.main_handler
  events:
    - apigw:
        parameters:
          protocols:
            - http
            - https
          environment: release
          endpoints:
            - path: /
              method: POST
  # layers:
  #   - name: ${output:${stage}:${app}:${name}-layer.name}
  #     version: ${output:${stage}:${app}:${name}-layer.version}